### ISSUE TITLE
listen EACCES: permission denied "5500" # App port

### ISSUE THREAD

**Issue by Rustiness** [ProdexOne/code-playground-backend#1]
Hi Anuj!

In ProdexOne/code-playground-backend folder, I run "npm dev" with admin previlegies, but the following error occurred:

## LOG:
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run dev --scripts-prepend-node-path=auto
Debugger listening on ws://127.0.0.1:53065/9d2e9bfb-aa76-4cfc-9e55-243392a404df
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> code-playground-backend@1.0.0 dev D:\workspace\ProdexOne\code-playground-backend
> nodemon src/server.ts

Debugger listening on ws://127.0.0.1:62755/8c23922e-11d6-4d53-a8bb-d302b6b2205c
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/server.ts`
Debugger listening on ws://127.0.0.1:62759/19eb74f7-ef99-4ccf-abad-dd563ecc9fad
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Error: listen EACCES: permission denied "5500"                             # App port
    at Server.setupListenHandle [as _listen2] (net.js:1299:21)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1461:5)
    at Function.listen (D:\workspace\ProdexOne\code-playground-backend\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (D:\workspace\ProdexOne\code-playground-backend\src\server.ts:23:20)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module.m._compile (D:\workspace\ProdexOne\code-playground-backend\node_modules\ts-node\src\index.ts:1295:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.require.extensions.<computed> [as .ts] (D:\workspace\ProdexOne\code-playground-backend\node_modules\ts-node\src\index.ts:1298:12)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at main (D:\workspace\ProdexOne\code-playground-backend\node_modules\ts-node\src\bin.ts:246:14)
    at Object.<anonymous> (D:\workspace\ProdexOne\code-playground-backend\node_modules\ts-node\src\bin.ts:382:3)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
Waiting for the debugger to disconnect...
[nodemon] app crashed - waiting for file changes before starting...

"code-playground-frontend" works normally with port 3000, and mongodb was also built with "mongodb://localhost:27017/myapp". Why is the backend like this?

## code-playground-backend > .env file
DB_URL=mongodb://localhost:27017/myapp      # MongoDB url
APP_PORT="5500"                             # App port
COOKIE_SECRET="my secret"                 # Cookie secret for signing
WEB_URL="http://localhost:3000"           # Frontend url

## code-playground-frontend > log
Compiled successfully!

You can now view code-playground-frontend in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.30.35:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

**Comment by Rustiness** [comment]
code-playground-backend> .env file set
DB_URL=mongodb://localhost:27017/myapp
APP_PORT=5500
COOKIE_SECRET=my_secret
WEB_URL=http://localhost:3000
